"use client";
import { useEffect, useState } from "react";
type Oldal = { id: string; slug: string; cim: string; bevezeto: string; szekciok: { cim: string; szoveg: string }[]; kintVan: boolean };
export default function TartalomKezelo() {
  const [oldalak,setOldalak]=useState<Oldal[]>([]); const [uzenet,setUzenet]=useState(""); const [szerkesztett,setSzerkesztett]=useState<Oldal|null>(null);
  async function betolt(){const r=await fetch("/api/kezeles/tartalmak",{cache:"no-store"});const d=await r.json();setOldalak(d.oldalak??[]);}
  useEffect(()=>{let elo=true;void fetch("/api/kezeles/tartalmak",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(elo)setOldalak(d.oldalak??[]);});return()=>{elo=false;};},[]);
  async function mentes(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const data={...(szerkesztett?{id:szerkesztett.id}:{}),slug:f.get("slug"),cim:f.get("cim"),bevezeto:f.get("bevezeto"),kintVan:f.get("kintVan")==="igen",szekciok:[{cim:String(f.get("szekcioCim")),szoveg:String(f.get("szekcioSzoveg"))}]};const r=await fetch("/api/kezeles/tartalmak",{method:szerkesztett?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const d=await r.json();setUzenet(d.hiba??"Az oldalt elmentettük.");if(r.ok){e.currentTarget.reset();setSzerkesztett(null);await betolt();}}
  async function kozzetesz(oldal:Oldal){const r=await fetch("/api/kezeles/tartalmak",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...oldal,kintVan:!oldal.kintVan})});const d=await r.json();setUzenet(d.hiba??"Az oldal állapotát mentettük.");await betolt();}
  return <div><form key={szerkesztett?.id??"uj"} onSubmit={mentes}><label>URL-végződés<input name="slug" placeholder="vasarlasi-utmutato" defaultValue={szerkesztett?.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label><label>Cím<input name="cim" defaultValue={szerkesztett?.cim} required maxLength={160} /></label><label>Bevezető<textarea name="bevezeto" defaultValue={szerkesztett?.bevezeto} required maxLength={1500} /></label><label>Első szakasz címe<input name="szekcioCim" defaultValue={szerkesztett?.szekciok[0]?.cim} required /></label><label>Első szakasz szövege<textarea name="szekcioSzoveg" defaultValue={szerkesztett?.szekciok[0]?.szoveg} required maxLength={5000} /></label><label><input name="kintVan" type="checkbox" value="igen" defaultChecked={szerkesztett?.kintVan} /> Mentés és azonnali közzététel</label><button type="submit">{szerkesztett?"Módosítás mentése":"Oldal létrehozása"}</button>{szerkesztett&&<button type="button" onClick={()=>setSzerkesztett(null)}>Új oldal</button>}</form>{uzenet&&<p role="status">{uzenet}</p>}<h2>Meglévő oldalak</h2><ul>{oldalak.map(o=><li key={o.id}><a href={`/oldal/${o.slug}`}>{o.cim}</a> · {o.kintVan?"közzétéve":"vázlat"} <button onClick={()=>setSzerkesztett(o)}>Szerkesztés</button> <button onClick={()=>void kozzetesz(o)}>{o.kintVan?"Visszavonás":"Közzététel"}</button></li>)}</ul></div>;
}
