import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { adminSutiNeve, hitelesitAdminMunkamenetet } from "@/auth/admin-munkamenet";
import { prisma } from "@/lib/adatbazis-kapcsolat";
export const dynamic = "force-dynamic";
const valasz=(d:unknown,s=200)=>NextResponse.json(d,{status:s,headers:{"Cache-Control":"private, no-store"}});
function eredet(request:NextRequest){try{return new URL(request.headers.get("origin")??"").origin===new URL(request.url).origin;}catch{return false;}}
export async function GET(request:NextRequest){if(!await hitelesitAdminMunkamenetet(request.cookies.get(adminSutiNeve)?.value,"edit_content"))return valasz({hiba:"Tartalomkezelői belépés szükséges."},401);try{return valasz({ertekelesek:await prisma.termekErtekeles.findMany({orderBy:[{allapot:"asc"},{createdAt:"desc"}],take:200,include:{termek:{select:{name:true,sku:true,slug:true}},rendeles:{select:{publicId:true}}}})});}catch{return valasz({hiba:"Az értékelések nem érhetők el."},503);}}
export async function PATCH(request:NextRequest){if(!eredet(request))return valasz({hiba:"A kérés eredete nem ellenőrizhető."},403);const admin=await hitelesitAdminMunkamenetet(request.cookies.get(adminSutiNeve)?.value,"edit_content");if(!admin)return valasz({hiba:"Tartalomkezelői belépés szükséges."},401);const p=z.object({id:z.string().min(1).max(80),allapot:z.enum(["PUBLISHED","REJECTED"])}).strict().safeParse(await request.json().catch(()=>null));if(!p.success)return valasz({hiba:"Az értékelés állapota hibás."},400);try{const updated=await prisma.$transaction(async tx=>{const r=await tx.termekErtekeles.update({where:{id:p.data.id,allapot:"PENDING"},data:{allapot:p.data.allapot,moderaltaId:admin.id,moderalvaAt:new Date()}});await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:p.data.allapot==="PUBLISHED"?"review_published":"review_rejected",targetType:"TermekErtekeles",targetId:r.id,details:{productId:r.productId,orderId:r.orderId}}});return r;});return valasz({ertekeles:updated});}catch{return valasz({hiba:"Az értékelés nem található vagy már elbírálták."},409);}}
